spring:
  profiles:
    active: local  # 기본 프로필을 local로 설정
  batch:
    job:
      enabled: false  # 애플리케이션 시작 시 자동으로 작업을 실행하지 않도록 설정
    jdbc:
      initialize-schema: always

  r2dbc:
    url: r2dbc:h2:mem:///stockdata;DB_CLOSE_DELAY=-1
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  # MongoDB 설정
  data:
    mongodb:
      uri: mongodb://quantai:quantaipassword@localhost:27017/stockdb?authSource=admin
      auto-index-creation: true

webclient:
  maxInMemorySize: 16777216  # 16MB
  connection:
    timeout: PT5S
    maxConnections: 500
    maxIdleTime: PT20S
    maxLifeTime: PT60S
    pendingAcquireTimeout: PT60S
    evictInBackground: PT120S
  read:
    timeout: PT5S
  write:
    timeout: PT5S

kis-client-mock:
  host: https://openapivts.koreainvestment.com
  port: 29443
  appKey: ${KIS_MOCK_APP_KEY:MISSING_APP_KEY}
  appSecret: ${KIS_MOCK_APP_SECRET:MISSING_APP_SECRET}
kis-client-real:
  host: https://openapi.koreainvestment.com
  port: 9443
  appKey: ${KIS_APP_KEY:MISSING_APP_KEY}
  appSecret: ${KIS_APP_SECRET:MISSING_APP_SECRET}

stock:
  batch:
    cron: "0 0 18 * * MON-FRI"  # 평일 오후 6시에 실행
    pageSize: 100
    stockCodes:
      - "005930"  # 삼성전자
      - "000660"  # SK하이닉스
      - "035420"  # NAVER
      - "035720"  # 카카오
      - "005380"  # 현대차
