spring:
  profiles:
    active: local
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  r2dbc:
    url: r2dbc:h2:mem:///stockdata;DB_CLOSE_DELAY=-1
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    mongodb:
      uri: mongodb://quantai:quantaipassword@localhost:27017/stockdb?authSource=admin
      auto-index-creation: true
      connection:
        pool:
          max-size: 100
          min-size: 5
          max-wait-time: PT15S
          max-connection-life-time: PT60S
          max-connection-idle-time: PT30S
        socket-timeout: PT5S
        connect-timeout: PT10S
        server-selection-timeout: PT15S
      read-preference: primaryPreferred
      write-concern:
        w: majority
        journal: true
        timeout: PT5S
      retry:
        writes: true
        reads: true
      heartbeat:
        frequency: PT10S
        min-frequency: PT0.5S

webclient:
  maxInMemorySize: 16777216
  connection:
    timeout: PT5S
    maxConnections: 500
    maxIdleTime: PT20S
    maxLifeTime: PT60S
    pendingAcquireTimeout: PT60S
    evictInBackground: PT120S
  read:
    timeout: PT5S
  write:
    timeout: PT5S

kis-client-mock:
  host: https://openapivts.koreainvestment.com
  port: 29443
  appKey: ${KIS_MOCK_APP_KEY:MISSING_APP_KEY}
  appSecret: ${KIS_MOCK_APP_SECRET:MISSING_APP_SECRET}
kis-client-real:
  host: https://openapi.koreainvestment.com
  port: 9443
  appKey: ${KIS_APP_KEY:MISSING_APP_KEY}
  appSecret: ${KIS_APP_SECRET:MISSING_APP_SECRET}

stock:
  batch:
    cron: "0 0 18 * * MON-FRI"
    pageSize: 100
    stockCodes:
      - "005930"
      - "000660"
      - "035420"
      - "035720"
      - "005380"
