version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: quantai-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: quantai
      MONGO_INITDB_ROOT_PASSWORD: quantaipassword
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - quantai-network
    command: ["--auth"]

  mongo-express:
    image: mongo-express:latest
    container_name: quantai-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: quantai
      ME_CONFIG_MONGODB_ADMINPASSWORD: quantaipassword
      ME_CONFIG_MONGODB_URL: mongodb://quantai:quantaipassword@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 1234
    depends_on:
      - mongodb
    networks:
      - quantai-network

networks:
  quantai-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
